name = "beltline-cloud"
main = "src/worker.js"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]

# Serve static assets from /public
assets = { directory = "./public" }

# Custom domain
routes = [
  { pattern = "beltlinecloud.com", custom_domain = true },
  { pattern = "www.beltlinecloud.com", custom_domain = true }
]

# D1 Database binding
[[d1_databases]]
binding = "DB_network"
database_name = "network"
database_id = "813a24be-1b72-426d-ab4a-5de6b6c076e7"
