name = "beltline-cloud"
main = "src/worker/work-main.js"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]

# 🔥 Your Worker is now bound to your API domain
routes = [
  { pattern = "api.beltlinecloud.com/*", zone_name = "beltlinecloud.com" }
]

[[d1_databases]]
binding = "DB_cloud"
database_name = "cloud"
database_id = "2f14ac6c-3299-4122-b63e-195c2cf8a3cc"

[[r2_buckets]]
binding = "R2"
bucket_name = "beltlinecloud"
preview_bucket_name = "beltlinecloud"

[vars]
R2_PUBLIC_URL = "media.beltlinecloud.com"
SITE_URL = "https://beltlinecloud.com"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
